### ISSUE TITLE
Import/Export Acres Broken?

### ISSUE THREAD

**Issue by Will-The-Lion** [kwsch/NLSE#12]
It seems I can't export and then import acres in the acre editor. Not even unedited. I can't import a freshly exported acre file from the same save. I get an error that says:

> Input file length is not a valid acre map. 
> Data Size: 84 
> Acre Count: 42

Also comparing this with the online one it appears that the [online acre editor](http://usuaris.tinet.cat/mark/acnl_editor/) doesn't have export or import but it does have border editing. Is that something that will be added to the .exe version? 

Love the tool it's incredibly helpful since I lost my old save when installing CFW.

Thanks!

**Comment by kwsch** [comment]
Probably would be best to let the online editor do the border editing; I'm not actively developing NLSE at this time.
