### ISSUE TITLE
Index 0 acre doesn't appear

### ISSUE THREAD

**Issue by jfgoncalves** [kwsch/NLSE#4]
Hi,

This is an issue that has been resolved on the web editor but not on this tool, the index 0 acre doesn't seems to appear in the town editor, or appears white instead of full green. 

[garden.dat file](http://cl.ly/3G1D3D312t0K)

**Comment by kwsch** [comment]
Implemented in latest commit:
https://github.com/kwsch/NLSE/commit/66a0a0d522a3437eb2eab3c077d0c74702ad2a50

Compiled Binary:
https://github.com/kwsch/NLSE/releases/tag/v0.5
