### ISSUE TITLE
Error: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by sanyajin** [kwsch/NLSE#6]
my NLSE stopped working for some reason a few weeks ago and I have no clue why.
I always get this error: http://i.imgur.com/DotvteJ.png (sorry it's in german but i can change it to english if you want to) and I don't know how to fix it. This error has been popping up since v0.2 (it still did on the latest versions) but keep up the good work I really enjoyed working with it!

**Comment by kwsch** [comment]
Please email me your save file so that I may debug :)

**Comment by D4rKT1mmy** [comment]
I have the same problem! Help D:
NLSE.09-24-15
http://i.imgur.com/CzI8dpJ.png
