### ISSUE TITLE
Changing town hall/train station roof colors breaks town ID

### ISSUE THREAD

**Issue by marcrobledo** [kwsch/NLSE#7]
Town hall and train station roof colors are hardcoded into town ID.
If you change any of them, then the town ID also changes, which means that all players in that town will act as strangers, since all references to their town ID won't match anymore.

The game is completely broken if players' town IDs don't match: users have reported they cannot send letters or donate to musem, but I'm pretty sure there are worse secondary effects.

**Comment by kwsch** [comment]
Looks like what needs to be done is an array copy for those 0x14 bytes across the entire Garden file when saving. Hopefully https://github.com/kwsch/NLSE/commit/9a7ea098eeb1f7acf7979b56e4708a1506b44d0e addresses this issue. 

For those who have broken their saves, they'll have to revert their town bytes manually to their original state; NLSE will propagate the Town's bytes to all the other instances only if they are equal.

edit: looks like you've got a similar solution :) :+1:
