### ISSUE TITLE
Incorrect badge order

### ISSUE THREAD

**Issue by marcrobledo** [kwsch/NLSE#9]
We've had an incorrect badge order since RAM hacking was available.
I have been writing the list from scratch lately, this is the correct order:
Fishes
Bugs
Marine
Fish collection
Bug collection
Marine collection
Balloons
Visiting other towns
Being visited
Watering flowers
Bank
Turnips
Medals
StreetPass
Weeds
Shopping
Letters
Refurbishing
Catalog
K.K. Slider
Home points
Time played
Helping neighbors
Dream Suite

**Comment by kwsch** [comment]
Thanks!

Implemented in latest commit: https://github.com/kwsch/NLSE/commit/bfd7aef6bed7ee7a710770d7478c6ed7dea155ae
